name: Database update

on:
  schedule:
    - cron: '00 12 * * *'

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: python -m pip install -r database/requirements.txt
      - name: execute py script
        run: cd database && python db_updater.py
      - name: commit updated database
        run: |
          git config --global user.name 'NWilde4'
          git config --global user.email ${{secrets.USER_EMAIL}}
          git add .
          git commit -m "automatic database update"
          git push
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: build
        run: npm run build:react
      - name: deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "covid-stats-hungary"
          heroku_email: "wilde.norman@yahoo.com"
          healthcheck: "https://covid-stats-hungary.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true

